name: ⚙️ Cypress component testing
on:
  pull_request:

env:
  CYPRESS_BASELINE_REPO: 'baseline'
  CYPRESS_RESULTS_FOLDER: 'projects/demo-cypress/tests-results'
  CYPRESS_BASELINE_SNAPSHOTS: 'projects/demo-cypress/tests-results/snapshots/baseline'
  CYPRESS_SNAPSHOTS_ARTIFACTS_KEY:
    'cypress-e2e-artifacts--${{ github.event.pull_request.head.sha || github.sha }}-${{ github.run_id }}-${{
    github.event.number }}'

jobs:
  cypress:
    runs-on: ubuntu-latest
    name: Component testing result
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/checkout@v4.2.0
        with:
          ref: ${{ github.base_ref }}
          path: ${{ env.CYPRESS_BASELINE_REPO }}
      - uses: taiga-family/ci/actions/setup/variables@v1.91.0
      - uses: taiga-family/ci/actions/setup/node@v1.91.0
      - run: |
          cd baseline
          npx nx component-test demo-cypress
          cd ../
          cp ${{ env.CYPRESS_BASELINE_REPO }}/${{ env.CYPRESS_BASELINE_SNAPSHOTS }} ${{ env.CYPRESS_BASELINE_SNAPSHOTS }}
          npx nx component-test demo-cypress
      - run: |
          npm install canvas
          npx ts-node ./scripts/visual-testing/combine-cypress-failed-screenshots.ts

      - name: Debug output
        continue-on-error: true
        run: tree ${{ env.CYPRESS_RESULTS_FOLDER }}  -L 1

      - name: Upload artifacts / ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
        uses: actions/upload-artifact@v4.4.0
        with:
          path: '${{ env.CYPRESS_RESULTS_FOLDER }}/**/*.diff.png'
          name: ${{ env.CYPRESS_SNAPSHOTS_ARTIFACTS_KEY }}
          if-no-files-found: ignore
          compression-level: 0
          retention-days: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
