name: ⚙️ Unit tests
on:
  push:
    branches:
      - main

jobs:
  test:
    if: ${{ !contains(github.head_ref, 'release/') }}
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: taiga-family/ci/actions/setup/variables@v1.91.0
      - uses: taiga-family/ci/actions/setup/node@v1.91.0
      - uses: taiga-family/ci/actions/run/node-info@v1.91.0
        id: info
      - run: npx nx run cdk:schematics --v=${{ steps.info.outputs.root-package-major-version }}
      - run: npm test
      - run: tree -L 2 ./coverage -P 'lcov.info'
      - uses: codecov/codecov-action@v4.6.0
        with:
          codecov_yml_path: ./.github/codecov.yml
          directory: ./coverage/
          flags: summary
          name: units

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
